version: "3.9"

services:
  server:
    image: supralog-technical-test
    build:
      context: .
      target: production
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mongo:7.0.3-jammy
    restart: always
    ports:
      - "27017:27017"